# --- 右手側 (トラックボール) ---

CONFIG_ZMK_SLEEP=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

# nice!nano v2 で "Incorrect product id 0xFF" エラーが出る場合は
# 以下のコメントを外してください
# CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
